version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  api:
    build: .
    container_name: api
    command: bash -c "uvicorn api_module.api:app --host 0.0.0.0"
    volumes:
      - ./media:/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
  capture:
    build: .
    container_name: capture
    command: bash -c "python capture_module/starter.py"
    env_file:
      - .env
    volumes:
      - ./media:/media
    depends_on:
      - redis
    ports:
      - 8081:8081
  detect:
    build: .
    container_name: detect
    command: bash -c "python detect_module/starter.py"
    env_file:
      - .env
    volumes:
      - ./media:/media
    depends_on:
      - redis
      - capture
    ports:
      - 8082:8082